const CONFIG={
API_BASE:window.location.origin,
ENDPOINTS:{
STATS:'/api/admin/stats',
BANS:'/api/admin/bans',
BAN_CLEAR:'/api/admin/bans/clear',
LOGS:'/api/admin/logs',
CACHE_CLEAR:'/api/admin/cache/clear',
SESSIONS_CLEAR:'/api/admin/sessions/clear',
WHITELIST:'/api/admin/whitelist',
SESSIONS:'/api/admin/sessions',
SUSPENDED:'/api/admin/suspended',
SUSPEND:'/api/admin/suspend',
UNSUSPEND:'/api/admin/unsuspend',
KILL_SESSION:'/api/admin/kill-session'
},
STORAGE:{ADMIN_KEY:'luarmor_admin_key',THEME:'luarmor_theme'},
INTERVALS:{STATS:30000,LOGS:15000,SESSIONS:10000},
TOAST_DURATION:4000
};
Object.freeze(CONFIG);
