const Whitelist={
wl:{userIds:[],hwids:[],owners:[]},
async init(){await this.load();this.bindEvents()},
async load(){const r=await API.get(CONFIG.ENDPOINTS.WHITELIST||'/api/admin/whitelist');if(r.success){this.wl=r.whitelist||{userIds:[],hwids:[],owners:[]};this.renderTable()}else{Utils.toast('Failed to load whitelist','error')}},
renderTable(){const tbody=document.getElementById('whitelistTableBody');if(!tbody)return;const all=[];(this.wl.userIds||[]).forEach(id=>all.push({type:'userId',value:id}));(this.wl.hwids||[]).forEach(h=>all.push({type:'hwid',value:h}));if(all.length===0){tbody.innerHTML=`<tr><td colspan="4" class="text-center" style="padding:40px"><div class="empty-state"><div class="empty-state-icon">📋</div><h4>No whitelist entries</h4><p class="text-muted">Add users or HWIDs to bypass protection</p></div></td></tr>`;return}tbody.innerHTML=all.map((e,i)=>`<tr class="animate-fadeIn"><td><span class="badge ${e.type==='userId'?'badge-info':'badge-purple'}">${e.type}</span></td><td><code class="text-primary">${Utils.escapeHtml(String(e.value))}</code></td><td>${e.type==='userId'?'Roblox User ID':'Hardware ID'}</td><td><button class="btn btn-danger btn-sm btn-icon" onclick="Whitelist.remove('${e.type}','${e.value}')" title="Remove">🗑️</button></td></tr>`).join('')},
bindEvents(){const search=document.getElementById('whitelistSearch');if(search){search.addEventListener('input',Utils.debounce(e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#whitelistTableBody tr').forEach(row=>{const text=row.textContent.toLowerCase();row.style.display=text.includes(q)?'':'none'})},300))}},
openAddModal(){const m=document.getElementById('addWhitelistModal');if(m){m.classList.add('active');document.getElementById('wlType').value='userId';document.getElementById('wlValue').value=''}},
closeAddModal(){const m=document.getElementById('addWhitelistModal');if(m)m.classList.remove('active')},
async add(){const type=document.getElementById('wlType').value;const value=document.getElementById('wlValue').value.trim();if(!value){Utils.toast('Enter a value','error');return}const btn=document.getElementById('addWlBtn');Utils.setLoading(btn,true);const r=await API.post('/api/admin/whitelist',{type,value});Utils.setLoading(btn,false);if(r.success){Utils.toast(r.msg||'Added to whitelist','success');this.closeAddModal();this.load()}else{Utils.toast(r.error||'Failed','error')}},
async remove(type,value){const ok=await Utils.confirm(`Remove ${value} from whitelist?`,'Remove');if(!ok)return;const r=await API.delete('/api/admin/whitelist',{type,value});if(r.success){Utils.toast('Removed from whitelist','success');this.load()}else{Utils.toast(r.error||'Failed','error')}},
render(){return`<div class="page-header"><div><h1 class="page-title">Whitelist</h1><p class="page-subtitle">Users and HWIDs that bypass all protection</p></div></div><div class="card animate-fadeInUp"><div class="card-header"><div class="actions-left"><div class="search-input-wrapper"><span class="search-icon">🔍</span><input type="text" id="whitelistSearch" class="form-input" placeholder="Search..." style="padding-left:40px;width:250px"></div></div><div class="actions-right"><button class="btn btn-secondary" onclick="Whitelist.load()">↻ Refresh</button><button class="btn btn-primary" onclick="Whitelist.openAddModal()">➕ Add Entry</button></div></div><div class="table-container"><table class="table"><thead><tr><th>Type</th><th>Value</th><th>Description</th><th>Actions</th></tr></thead><tbody id="whitelistTableBody"><tr><td colspan="4" class="text-center" style="padding:40px"><div class="spinner"></div></td></tr></tbody></table></div></div><div class="card animate-fadeInUp" style="margin-top:var(--space-6)"><div class="card-header"><h3 class="card-title"><span class="card-title-icon">👑</span>Owners</h3></div><div class="card-body"><p class="text-secondary">Owner IDs are configured via environment variables. Script will terminate if owner joins the same server.</p><div style="margin-top:var(--space-4)">${(this.wl.owners||[]).length>0?(this.wl.owners||[]).map(id=>`<span class="badge badge-warning" style="margin-right:8px">${id}</span>`).join(''):'<span class="text-muted">No owners configured</span>'}</div></div></div><div class="modal-overlay" id="addWhitelistModal"><div class="modal"><div class="modal-header"><h3 class="modal-title">➕ Add to Whitelist</h3><button class="modal-close" onclick="Whitelist.closeAddModal()">✕</button></div><div class="modal-body"><div class="form-group"><label class="form-label">Type</label><select id="wlType" class="form-input form-select"><option value="userId">User ID</option><option value="hwid">HWID</option></select></div><div class="form-group"><label class="form-label">Value</label><input type="text" id="wlValue" class="form-input" placeholder="Enter User ID or HWID"></div></div><div class="modal-footer"><button class="btn btn-secondary" onclick="Whitelist.closeAddModal()">Cancel</button><button class="btn btn-primary" id="addWlBtn" onclick="Whitelist.add()">➕ Add</button></div></div></div>`}
};
