const express=require('express'),axios=require('axios'),crypto=require('crypto'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),path=require('path'),fs=require('fs'),config=require('./config'),db=require('./lib/redis');
const app=express(),SESSIONS=new Map(),dynamicWhitelist={userIds:new Set(),hwids:new Set()};
const BOT_PATTERNS=['python','python-requests','aiohttp','httpx','curl','wget','libcurl','axios','node-fetch','got/','undici','superagent','java/','okhttp','apache-http','go-http','golang','ruby','perl','php/','postman','insomnia','paw/','bot','crawler','spider','scraper','slurp','googlebot','bingbot','yandex','facebookexternalhit','twitterbot','discordbot','telegrambot','burp','fiddler','charles','mitmproxy','nmap','nikto','sqlmap','nuclei','httpie','scanner','checker','monitor','probe'];
const BROWSER_HEADERS=['sec-fetch-dest','sec-fetch-mode','sec-fetch-site','sec-ch-ua','sec-ch-ua-mobile','upgrade-insecure-requests'];
const EXECUTOR_HEADERS=['x-hwid','x-roblox-id','x-place-id','x-job-id','x-session-id'];
const ALLOWED_EXECUTORS=['synapse','synapsex','script-ware','scriptware','delta','fluxus','krnl','oxygen','evon','hydrogen','vegax','trigon','comet','solara','wave','zorara','codex','celery','swift','sirhurt','electron','sentinel','coco','temple','valyse','nihon','jjsploit','arceus','roblox','wininet','win32'];
function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
function hmac(d,k){return crypto.createHmac('sha256',k).update(d).digest('hex')}
function secureCompare(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;try{return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}catch{return false}}
function getIP(r){return(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.headers['x-real-ip']||r.ip||'0.0.0.0'}
function getHWID(r){return r.headers['x-hwid']||null}
function genSessionKey(u,h,t,s){return hmac(`${u}:${h}:${t}`,s).substring(0,32)}
function getClientType(req){const ua=(req.headers['user-agent']||'').toLowerCase(),headers=req.headers;const execScore=EXECUTOR_HEADERS.filter(h=>headers[h]).length;const browScore=BROWSER_HEADERS.filter(h=>headers[h]).length;const isBotUA=BOT_PATTERNS.some(p=>ua.includes(p));const isExecUA=ALLOWED_EXECUTORS.some(e=>ua.includes(e));if(isBotUA&&execScore===0)return'bot';if(browScore>=2)return'browser';if(!ua||ua.length<10){if(execScore>=2)return'executor';return'bot'}if(execScore>=2)return'executor';if(isExecUA)return'executor';if(ua.includes('mozilla')&&execScore===0&&!isExecUA){const accept=headers['accept']||'';if(accept.includes('text/html'))return'browser';return'unknown'}return'unknown'}
function shouldBlock(req){return['bot','browser','unknown'].includes(getClientType(req))}
function genFakeScript(){const ts=Date.now(),rS=(l)=>{const c='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_';let s=c[Math.floor(Math.random()*26)];for(let i=1;i<l;i++)s+=c[Math.floor(Math.random()*c.length)];return s},rH=(l)=>{let h='';for(let i=0;i<l;i++)h+=Math.floor(Math.random()*16).toString(16);return h},rN=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;const v=Array(30).fill(0).map(()=>rS(rN(4,12)));const styles=[()=>`--[[ Luraph v${rN(12,15)}.${rN(0,9)}.${rN(0,9)} | ${rH(32)} ]]\nlocal ${v[0]},${v[1]},${v[2]},${v[3]};\nlocal ${v[4]}=(function()\nlocal ${v[5]}={${Array(rN(20,40)).fill(0).map(()=>`"\\${rN(100,255)}\\${rN(100,255)}"`).join(',')}};\nlocal ${v[6]}=0x${rH(4)};\nfor ${v[7]}=1,#${v[5]} do\n${v[6]}=bit32.bxor(${v[6]},string.byte(${v[5]}[${v[7]}],1) or 0);\nend\nreturn ${v[6]};\nend)();\nlocal ${v[8]}=setmetatable({},{__index=function(${v[9]},${v[10]})\nreturn rawget(${v[9]},${v[10]}) or error("Protected",0);\nend,__metatable="${rS(16)}"});\n--[[ Checksum: ${rH(64)} | TS: ${ts} ]]\nerror("Verification failed",0);`,()=>`--[=[ IronBrew2 ${rN(1,3)}.${rN(0,9)}${rN(0,9)} ]=]\nlocal ${v[0]}="${rH(64)}";\nlocal ${v[1]}=(function(${v[2]})\nlocal ${v[3]}={};\nfor ${v[4]}=1,#${v[2]} do\n${v[3]}[${v[4]}]=bit32.bxor(string.byte(${v[2]},${v[4]}),${rN(50,200)});\nend;\nreturn ${v[3]};\nend)("${rS(32)}");\nlocal ${v[5]}=coroutine.wrap(function()\nwhile true do\ncoroutine.yield(math.random(0,${rN(10000,99999)}));\nend;\nend);\nfor ${v[6]}=1,${rN(100,500)} do\n${v[1]}[${v[6]}]=(${v[5]}()+${v[1]}[${v[6]} % #${v[1]}+1])%256;\nend;\n--[=[ VM Encrypted | Key: ${rH(32)} ]=]`,()=>`--[[\nMoonsec V${rN(1,2)} | Hash: ${rH(40)}\n]]\nlocal ${v[0]}=table.create(${rN(100,300)});\nlocal ${v[1]}=0x${rH(6)};\nlocal function ${v[3]}(${v[4]})\nlocal ${v[5]}="";\nfor ${v[6]}=1,#${v[4]} do\n${v[5]}=${v[5]}..string.char(bit32.bxor(string.byte(${v[4]},${v[6]}),${v[1]}%256));\n${v[1]}=bit32.lrotate(${v[1]},${rN(3,7)});\nend;\nreturn ${v[5]};\nend;\nlocal ${v[7]}=${v[3]}("${rS(48)}");\npcall(function() error(${v[7]},0) end);`];return styles[Math.floor(Math.random()*styles.length)]()}
function encryptLoader(script,key){const kB=Buffer.from(key),sB=Buffer.from(script),enc=[];for(let i=0;i<sB.length;i++)enc.push(sB[i]^kB[i%kB.length]);return Buffer.from(enc).toString('base64')}
function genLoaderKey(req){const c=[req.headers['x-hwid']||'',req.headers['x-roblox-id']||'',req.headers['x-place-id']||'',config.LOADER_KEY||config.SECRET_KEY];return crypto.createHash('md5').update(c.join(':')).digest('hex').substring(0,16)}
function getLoader(url){return`local S="${url}" local H=game:GetService("HttpService") local P=game:GetService("Players") local G=game:GetService("StarterGui") local L=P.LocalPlayer local function n(t,x,d)pcall(function()G:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3})end)end local function hw()local s,r=pcall(function()if gethwid then return gethwid()end;if getexecutorname then return getexecutorname()..tostring(L.UserId)end;return"NK_"..tostring(L.UserId)end)return s and r or"UNK"end local function hp(u,d)local r=(syn and syn.request)or request or http_request or(http and http.request)if not r then return nil end;local s,res=pcall(function()return r({Url=u,Method="POST",Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=hw(),["x-roblox-id"]=tostring(L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId},Body=H:JSONEncode(d)})end)if not s or not res or res.StatusCode~=200 then return nil end;local ps,pd=pcall(function()return H:JSONDecode(res.Body)end)return ps and pd or nil end local function xd(d,k)local r={}for i=1,#d do r[i]=string.char(bit32.bxor(d[i],k:byte((i-1)%#k+1)))end;return table.concat(r)end local function sv(p)if not p or not p.type then return 0 end;if p.type=="math"then local a,b,c,op=p.puzzle.a,p.puzzle.b,p.puzzle.c,p.puzzle.op;if op=="+"then return(a+b)*c elseif op=="-"then return(a-b)*c else return(a*b)+c end elseif p.type=="bitwise"then local x,y,op=p.puzzle.x,p.puzzle.y,p.puzzle.op;if op=="xor"then return bit32.bxor(x,y)elseif op=="and"then return bit32.band(x,y)else return bit32.bor(x,y)end elseif p.type=="sequence"then local s=p.puzzle.seq;return s[4]+(s[2]-s[1])elseif p.puzzle and p.puzzle.numbers then local sum=0;for _,x in ipairs(p.puzzle.numbers)do sum=sum+x end;return sum end;return 0 end n("🔄","Connecting...",2) local c=hp(S.."/api/auth/challenge",{userId=L.UserId,hwid=hw(),placeId=game.PlaceId}) if not c or not c.success then n("❌",c and c.error or"Failed",5)return end local v=hp(S.."/api/auth/verify",{challengeId=c.challengeId,solution=sv(c),timestamp=os.time()}) if not v or not v.success then n("❌",v and v.error or"Failed",5)return end n("✅","Loading...",2) local fs;if v.mode=="raw"then fs=v.script else local p={}for i,ch in ipairs(v.chunks)do p[i]=xd(ch,v.key)end;fs=table.concat(p)end local fn,err=loadstring(fs) if fn then fs=nil;v=nil;c=nil;pcall(fn)else n("❌","Error",5)end`}
function getEncodedLoader(url,req){const key=genLoaderKey(req),enc=encryptLoader(getLoader(url),key);return`local k="${key}"local d="${enc}"local function x(s,k)local r={}local b={}for i=1,#s do b[i]=s:byte(i)end;for i=1,#b do r[i]=string.char(bit32.bxor(b[i],k:byte((i-1)%#k+1)))end;return table.concat(r)end;local function b(s)local t={}local c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"for i=1,64 do t[c:sub(i,i)]=i-1 end;s=s:gsub("[^"..c.."=]","")local r={}local n=1;for i=1,#s,4 do local a,b,c,d=t[s:sub(i,i)]or 0,t[s:sub(i+1,i+1)]or 0,t[s:sub(i+2,i+2)]or 0,t[s:sub(i+3,i+3)]or 0;local v=a*262144+b*4096+c*64+d;r[n]=string.char(bit32.rshift(v,16)%256)n=n+1;if s:sub(i+2,i+2)~="="then r[n]=string.char(bit32.rshift(v,8)%256)n=n+1 end;if s:sub(i+3,i+3)~="="then r[n]=string.char(v%256)n=n+1 end end;return table.concat(r)end;loadstring(x(b(d),k))()`}
async function checkWhitelist(hwid,userId){if(userId){const uid=parseInt(userId);if(config.WHITELIST_USER_IDS&&config.WHITELIST_USER_IDS.includes(uid))return true;if(dynamicWhitelist.userIds.has(uid))return true}if(hwid){if(config.WHITELIST_HWIDS&&config.WHITELIST_HWIDS.includes(hwid))return true;if(dynamicWhitelist.hwids.has(hwid))return true}return false}
function isOwner(userId){if(!userId)return false;const uid=parseInt(userId);return config.OWNER_USER_IDS&&config.OWNER_USER_IDS.includes(uid)}
async function logAccess(r,a,s,d={}){const log={ip:getIP(r),hwid:getHWID(r),ua:(r.headers['user-agent']||'').substring(0,100),action:a,success:s,path:r.path,client:getClientType(r),ts:new Date().toISOString(),...d};await db.addLog(log);return log}
function genChallenge(){const types=['math','bitwise','sequence','sum'],type=types[Math.floor(Math.random()*types.length)];switch(type){case'math':const op=['+','-','*'][Math.floor(Math.random()*3)],a=Math.floor(Math.random()*50)+10,b=Math.floor(Math.random()*20)+5,c=Math.floor(Math.random()*10)+1;let ans;if(op==='+')ans=(a+b)*c;else if(op==='-')ans=(a-b)*c;else ans=(a*b)+c;return{type:'math',puzzle:{a,b,c,op},answer:ans};case'bitwise':const x=Math.floor(Math.random()*200)+50,y=Math.floor(Math.random()*100)+20,bop=['xor','and','or'][Math.floor(Math.random()*3)];let bans;if(bop==='xor')bans=x^y;else if(bop==='and')bans=x&y;else bans=x|y;return{type:'bitwise',puzzle:{x,y,op:bop},answer:bans};case'sequence':const start=Math.floor(Math.random()*15)+1,step=Math.floor(Math.random()*8)+2;return{type:'sequence',puzzle:{seq:[start,start+step,start+step*2,start+step*3]},answer:start+step*4};default:const nums=Array.from({length:5},()=>Math.floor(Math.random()*50)+1);return{type:'sum',puzzle:{numbers:nums},answer:nums.reduce((a,b)=>a+b,0)}}}
function isObfuscated(s){if(!s)return false;return[/Luraph/i,/Moonsec/i,/IronBrew/i,/Prometheus/i,/PSU/i].some(r=>r.test(s.substring(0,500)))}
async function getScript(){const cached=await db.getCachedScript();if(cached)return cached;if(!config.SCRIPT_SOURCE_URL)return null;try{const res=await axios.get(config.SCRIPT_SOURCE_URL,{timeout:30000,headers:{'User-Agent':'Roblox/WinInet'},maxContentLength:50000000});if(typeof res.data==='string'&&res.data.length>50){await db.setCachedScript(res.data);return res.data}}catch(e){console.error('Script fetch error:',e.message)}return null}
function wrapScript(script,serverUrl){const o=(config.OWNER_USER_IDS||[]).join(','),w=(config.WHITELIST_USER_IDS||[]).join(','),sid=crypto.randomBytes(16).toString('hex');return`local _O={${o}} local _W={${w}} local _B="${serverUrl}/api/ban" local _SID="${sid}" local _A=true local P=game:GetService("Players") local L=P.LocalPlayer local S=game:GetService("StarterGui") local function n(t,x,d)pcall(function()S:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3})end)end local function isW(u)for _,i in ipairs(_W)do if u==i then return true end end;return false end local function isO(u)for _,i in ipairs(_O)do if u==i then return true end end;return false end for _,p in pairs(P:GetPlayers())do if isO(p.UserId)and p~=L then n("⚠️","Owner detected",3)return end end P.PlayerAdded:Connect(function(p)if isO(p.UserId)then n("⚠️","Owner joined",3)_A=false end end) ${script}`}
const viewsPath=path.join(__dirname,'views');
const TRAP_HTML=fs.existsSync(path.join(viewsPath,'trap/index.html'))?fs.readFileSync(path.join(viewsPath,'trap/index.html'),'utf8'):`<!DOCTYPE html><html><head><title>403</title></head><body style="background:#0a0a0f;color:#fff;display:flex;justify-content:center;align-items:center;height:100vh;font-family:sans-serif"><div style="text-align:center"><h1 style="font-size:60px">🛡️</h1><h2 style="color:#ef4444">Access Denied</h2><p style="color:#666">HTTP 403</p></div></body></html>`;
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false,crossOriginResourcePolicy:false}));
app.use(cors({origin:'*',methods:['GET','POST','DELETE','OPTIONS'],allowedHeaders:['Content-Type','x-admin-key','x-hwid','x-roblox-id','x-place-id','x-job-id','x-session-id']}));
app.use(express.json({limit:'10mb'}));
app.set('trust proxy',1);
app.use(rateLimit({windowMs:60000,max:100,keyGenerator:r=>getIP(r)}));
app.use('/admin/css',express.static(path.join(viewsPath,'admin/css')));
app.use('/admin/js',express.static(path.join(viewsPath,'admin/js')));
app.use(async(req,res,next)=>{const ban=await db.isBanned(null,getIP(req),null);if(ban.blocked){const ct=getClientType(req);if(ct==='browser')return res.status(403).type('html').send(TRAP_HTML);return res.status(403).type('text/plain').send(genFakeScript())}next()});
const adminAuth=(req,res,next)=>{const key=req.headers['x-admin-key']||req.query.key;if(!key)return res.status(403).json({success:false,error:'Unauthorized'});if(!config.ADMIN_KEY)return res.status(500).json({success:false,error:'Server misconfigured'});if(!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({success:false,error:'Unauthorized'});next()};
app.get('/admin',(req,res)=>{const f=path.join(viewsPath,'admin/index.html');if(fs.existsSync(f))res.sendFile(f);else res.status(404).send('Not found')});
app.get('/',(req,res)=>{const ct=getClientType(req);if(ct==='browser')return res.status(403).type('html').send(TRAP_HTML);if(shouldBlock(req))return res.status(403).type('text/plain').send(genFakeScript());res.json({status:'ok',v:'1.0.0'})});
app.get('/health',(req,res)=>res.json({status:'ok',redis:db.isRedisConnected?.()??false}));
app.get(['/loader','/api/loader.lua','/api/loader','/l'],async(req,res)=>{const ct=getClientType(req),ip=getIP(req),hwid=getHWID(req);await logAccess(req,'LOADER',ct==='executor',{clientType:ct});if(shouldBlock(req)){console.log(`[Loader] Blocked ${ct} from ${ip}`);return res.status(200).type('text/plain').send(genFakeScript())}const userId=req.headers['x-roblox-id'];const isWL=await checkWhitelist(hwid,userId);const url=process.env.RENDER_EXTERNAL_URL||`${req.protocol}://${req.get('host')}`;if(config.ENCODE_LOADER!==false&&!isWL){res.type('text/plain').send(getEncodedLoader(url,req))}else{res.type('text/plain').send(getLoader(url))}});
app.post('/api/auth/challenge',async(req,res)=>{const ct=getClientType(req);if(shouldBlock(req)){await logAccess(req,'CHALLENGE_BLOCKED',false,{clientType:ct});return res.status(403).json({success:false,error:'Access denied'})}const{userId,hwid,placeId}=req.body;if(!userId||!placeId)return res.status(400).json({success:false,error:'Missing fields'});if(config.REQUIRE_HWID&&!hwid)return res.status(400).json({success:false,error:'HWID required'});const uid=parseInt(userId),pid=parseInt(placeId);if(isNaN(uid)||isNaN(pid))return res.status(400).json({success:false,error:'Invalid format'});const ip=getIP(req);const isWL=await checkWhitelist(hwid,uid);if(!isWL){const ban=await db.isBanned(hwid,ip,uid);if(ban.blocked)return res.status(403).json({success:false,error:'Banned: '+ban.reason})}if(config.ALLOWED_PLACE_IDS&&config.ALLOWED_PLACE_IDS.length>0&&!config.ALLOWED_PLACE_IDS.includes(pid)&&!isWL){return res.status(403).json({success:false,error:'Game not authorized'})}await logAccess(req,'CHALLENGE',true,{clientType:ct,whitelisted:isWL});const id=crypto.randomBytes(16).toString('hex'),chal=genChallenge();await db.setChallenge(id,{id,userId:uid,hwid:hwid||'none',placeId:pid,ip,whitelisted:isWL,...chal},120);res.json({success:true,challengeId:id,type:chal.type,puzzle:chal.puzzle,expiresIn:120})});
app.post('/api/auth/verify',async(req,res)=>{const ct=getClientType(req);if(shouldBlock(req))return res.status(403).json({success:false,error:'Access denied'});const{challengeId,solution,timestamp}=req.body;if(!challengeId||solution===undefined||!timestamp)return res.status(400).json({success:false,error:'Missing fields'});const challenge=await db.getChallenge(challengeId);if(!challenge)return res.status(403).json({success:false,error:'Challenge expired'});if(challenge.ip!==getIP(req))return res.status(403).json({success:false,error:'IP mismatch'});if(parseInt(solution)!==challenge.answer)return res.status(403).json({success:false,error:'Wrong solution'});await db.deleteChallenge(challengeId);const script=await getScript();if(!script)return res.status(500).json({success:false,error:'Script not configured'});const url=process.env.RENDER_EXTERNAL_URL||`${req.protocol}://${req.get('host')}`;const wrapped=wrapScript(script,url);const isObf=config.SCRIPT_ALREADY_OBFUSCATED||isObfuscated(script);const sessionId=crypto.randomBytes(16).toString('hex');SESSIONS.set(sessionId,{hwid:challenge.hwid,ip:challenge.ip,userId:challenge.userId,created:Date.now()});await logAccess(req,'VERIFY_SUCCESS',true,{userId:challenge.userId});if(isObf)return res.json({success:true,mode:'raw',script:wrapped,sessionId});const key=genSessionKey(challenge.userId,challenge.hwid,timestamp,config.SECRET_KEY);const chunks=[];for(let i=0;i<wrapped.length;i+=1500){const chunk=wrapped.substring(i,i+1500),enc=[];for(let j=0;j<chunk.length;j++)enc.push(chunk.charCodeAt(j)^key.charCodeAt(j%key.length));chunks.push(enc)}res.json({success:true,mode:'encrypted',key,chunks,sessionId})});
app.post('/api/heartbeat',async(req,res)=>{const{sessionId,hwid}=req.body;if(!sessionId||!hwid)return res.json({success:true,action:'CONTINUE'});const session=SESSIONS.get(sessionId);if(!session)return res.json({success:true,action:'CONTINUE'});const ban=await db.isBanned(hwid,getIP(req),session.userId);if(ban.blocked)return res.json({success:false,action:'TERMINATE',reason:'Banned'});session.lastSeen=Date.now();res.json({success:true,action:'CONTINUE'})});
app.post('/api/ban',async(req,res)=>{const{hwid,playerId,reason,sessionId}=req.body;if(!hwid&&!playerId)return res.status(400).json({error:'Missing id'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const banData={ip:getIP(req),reason:reason||'Auto',banId,ts:new Date().toISOString()};if(hwid)await db.addBan(hwid,{hwid,...banData});if(playerId)await db.addBan(String(playerId),{playerId,...banData});if(sessionId)SESSIONS.delete(sessionId);await logAccess(req,'BAN_ADDED',true,{hwid,playerId,reason});res.json({success:true,banId})});
app.get('/api/admin/stats',adminAuth,async(req,res)=>{try{const stats=await db.getStats();res.json({success:true,stats,sessions:SESSIONS.size,ts:new Date().toISOString()})}catch(e){res.status(500).json({success:false,error:'Failed'})}});
app.get('/api/admin/logs',adminAuth,async(req,res)=>{const limit=Math.min(parseInt(req.query.limit)||50,500);const logs=await db.getLogs(limit);res.json({success:true,logs})});
app.get('/api/admin/bans',adminAuth,async(req,res)=>{const bans=await db.getAllBans();res.json({success:true,bans})});
app.post('/api/admin/bans',adminAuth,async(req,res)=>{const{hwid,ip,playerId,reason}=req.body;if(!hwid&&!ip&&!playerId)return res.status(400).json({success:false,error:'Required'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const data={reason:reason||'Manual',banId,ts:new Date().toISOString()};if(hwid)await db.addBan(hwid,{hwid,...data});if(playerId)await db.addBan(String(playerId),{playerId,...data});if(ip)await db.addBan(ip,{ip,...data});res.json({success:true,banId})});
app.delete('/api/admin/bans/:id',adminAuth,async(req,res)=>{const removed=await db.removeBanById(req.params.id);res.json({success:removed})});
app.post('/api/admin/bans/clear',adminAuth,async(req,res)=>{const count=await db.clearBans();res.json({success:true,cleared:count})});
app.post('/api/admin/cache/clear',adminAuth,async(req,res)=>{await db.setCachedScript(null);res.json({success:true})});
app.post('/api/admin/sessions/clear',adminAuth,async(req,res)=>{const count=SESSIONS.size;SESSIONS.clear();res.json({success:true,cleared:count})});
app.get('/api/admin/whitelist',adminAuth,async(req,res)=>{res.json({success:true,whitelist:{userIds:[...(config.WHITELIST_USER_IDS||[]),...dynamicWhitelist.userIds],hwids:[...(config.WHITELIST_HWIDS||[]),...dynamicWhitelist.hwids],owners:config.OWNER_USER_IDS||[]}})});
app.post('/api/admin/whitelist',adminAuth,async(req,res)=>{const{type,value}=req.body;if(!type||!value)return res.status(400).json({success:false,error:'Missing fields'});if(type==='userId'){dynamicWhitelist.userIds.add(parseInt(value));res.json({success:true,msg:`Added userId ${value}`})}else if(type==='hwid'){dynamicWhitelist.hwids.add(value);res.json({success:true,msg:`Added hwid ${value}`})}else{res.status(400).json({success:false,error:'Invalid type'})}});
app.delete('/api/admin/whitelist',adminAuth,async(req,res)=>{const{type,value}=req.body;if(type==='userId')dynamicWhitelist.userIds.delete(parseInt(value));else if(type==='hwid')dynamicWhitelist.hwids.delete(value);res.json({success:true})});
app.use('*',(req,res)=>{const ct=getClientType(req);if(ct==='browser')return res.status(404).type('html').send(TRAP_HTML);if(shouldBlock(req))return res.status(403).type('text/plain').send(genFakeScript());res.status(404).json({error:'Not found'})});
setInterval(()=>{const now=Date.now();for(const[k,v]of SESSIONS)if(now-v.created>7200000)SESSIONS.delete(k)},300000);
const PORT=process.env.PORT||config.PORT||3000;
app.listen(PORT,'0.0.0.0',()=>{console.log(`\n🛡️ Script Shield running on port ${PORT}\n📍 Admin: http://localhost:${PORT}/admin\n📦 Loader: http://localhost:${PORT}/loader\n`)});
