const https=require('https');
const config=require('../config');
const WEBHOOK_URL=process.env.DISCORD_WEBHOOK||config.DISCORD_WEBHOOK||'';
const COLORS={success:0x22c55e,warning:0xf59e0b,error:0xef4444,info:0x8b5cf6,ban:0xff0000,execution:0x3b82f6};
function parseWebhookUrl(url){if(!url)return null;const match=url.match(/discord\.com\/api\/webhooks\/(\d+)\/(.+)/);if(!match)return null;return{id:match[1],token:match[2]}}
async function send(embeds,content=''){const parsed=parseWebhookUrl(WEBHOOK_URL);if(!parsed){console.log('[Webhook] No webhook configured');return false}const payload=JSON.stringify({content,embeds,username:'Script Shield',avatar_url:'https://i.imgur.com/8nLFCVP.png'});return new Promise((resolve)=>{const req=https.request({hostname:'discord.com',port:443,path:`/api/webhooks/${parsed.id}/${parsed.token}`,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},res=>{resolve(res.statusCode===204||res.statusCode===200)});req.on('error',()=>resolve(false));req.write(payload);req.end()})}
async function execution(data){const{userId,hwid,placeId,ip,executor,key}=data;await send([{title:'✅ Script Executed',color:COLORS.execution,fields:[{name:'👤 User ID',value:`\`${userId||'N/A'}\``,inline:true},{name:'🎮 Place ID',value:`\`${placeId||'N/A'}\``,inline:true},{name:'💻 Executor',value:`\`${executor||'Unknown'}\``,inline:true},{name:'🔑 HWID',value:`\`${(hwid||'N/A').substring(0,20)}...\``,inline:true},{name:'🌐 IP',value:`\`${ip||'N/A'}\``,inline:true},{name:'🔐 Key',value:`\`${key?key.substring(0,8)+'...':'No Key'}\``,inline:true}],timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
async function suspicious(data){const{userId,hwid,ip,reason,tool,action}=data;await send([{title:'⚠️ Suspicious Activity',color:COLORS.warning,fields:[{name:'👤 User ID',value:`\`${userId||'N/A'}\``,inline:true},{name:'🔑 HWID',value:`\`${(hwid||'N/A').substring(0,20)}...\``,inline:true},{name:'🌐 IP',value:`\`${ip||'N/A'}\``,inline:true},{name:'🔍 Reason',value:`\`${reason||'Unknown'}\``,inline:true},{name:'🛠️ Tool Detected',value:`\`${tool||'N/A'}\``,inline:true},{name:'⚡ Action',value:`\`${action||'Kicked'}\``,inline:true}],timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
async function ban(data){const{userId,hwid,ip,reason,bannedBy,banId}=data;await send([{title:'🚫 User Banned',color:COLORS.ban,fields:[{name:'👤 User ID',value:`\`${userId||'N/A'}\``,inline:true},{name:'🔑 HWID',value:`\`${(hwid||'N/A').substring(0,20)}...\``,inline:true},{name:'🌐 IP',value:`\`${ip||'N/A'}\``,inline:true},{name:'📝 Reason',value:`\`${reason||'No reason'}\``,inline:true},{name:'👮 Banned By',value:`\`${bannedBy||'System'}\``,inline:true},{name:'🆔 Ban ID',value:`\`${banId||'N/A'}\``,inline:true}],timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
async function keyEvent(data){const{event,key,userId,hwid}=data;const titles={activated:'🔑 Key Activated',expired:'⏰ Key Expired',hwidReset:'🔄 HWID Reset',revoked:'❌ Key Revoked'};await send([{title:titles[event]||'🔑 Key Event',color:event==='activated'?COLORS.success:COLORS.warning,fields:[{name:'🔐 Key',value:`\`${key?key.substring(0,12)+'...':'N/A'}\``,inline:true},{name:'👤 User ID',value:`\`${userId||'N/A'}\``,inline:true},{name:'🔑 HWID',value:`\`${(hwid||'N/A').substring(0,16)}...\``,inline:true}],timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
async function serverStart(){await send([{title:'🚀 Server Started',color:COLORS.success,description:'Script Shield server is now online and ready.',timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
async function error(data){const{error,context,stack}=data;await send([{title:'❌ Error Occurred',color:COLORS.error,fields:[{name:'📍 Context',value:`\`${context||'Unknown'}\``,inline:true},{name:'❌ Error',value:`\`\`\`${(error||'Unknown error').substring(0,500)}\`\`\``,inline:false}],timestamp:new Date().toISOString(),footer:{text:'Script Shield'}}])}
module.exports={send,execution,suspicious,ban,keyEvent,serverStart,error,isConfigured:()=>!!WEBHOOK_URL};
